### ISSUE TITLE
Problem using phosphor with OpenMRS

### ISSUE THREAD

**Issue by goatgoose1142** [gmu-swe/phosphor#116]
Hello,

I'm having an issue using phosphor with [OpenMRS](https://github.com/openmrs/openmrs-core). Mostly, it seems to work, however, when I add one of the reference application modules, phosphor prevents OpenMRS from starting (all of the other modules seem to work).

The following is the entire log of starting tomcat with an OpenMRS war:
https://pastebin.com/raw/Bg4e3suu

Potentially relevant information about my OS, tomcat version, JVM version, etc, is at the top of that log.

This is just the section where phosphor complains:
https://pastebin.com/raw/U89MRuDQ

After the last line in the complete log, OpenMRS just sits at 100% cpu seemingly doing nothing.

These are the steps I took to produce the problem:
- I Downloaded "Platform 2.2.0 WAR" and "Reference Application 2.9.0 Addons" from "Individual Components for Advanced Installation" here: https://openmrs.org/download/
- I Placed the OpenMRS war in my tomcat directory
- I ran catalina to generate the ~/.OpenMRS folder and then copied the modules from the reference application addons download into my OpenMRS modules folder
- I executed the following:
```
/path/to/java /path/to/Phosphor-0.0.4-SNAPSHOT.jar -multiTaint /path/to/jre jre-inst
export JAVA_HOME=/path/to/jre-inst
export JRE_HOME=/path/to/jre-inst
export JAVA_OPTS="-Xbootclasspath/a:/path/to/Phosphor-0.0.4-SNAPSHOT.jar -javaagent:/path/to/Phosphor-0.0.4-SNAPSHOT.jar"
catalina run
```
If I then remove the "webservices.rest-2.24.0.omod" module from my OpenMRS modules directory, it works fine.

Any idea what might be the problem here?
Thanks!

**Comment by jon-bell** [comment]
Is there some file like debug/jdk.nashorn.internal.scripts.Script$^eval_.class generated? If so, can you post it here (greatly helps me reproduce). Looks like we have some bug with some invoke dynamic case.

**Comment by goatgoose1142** [comment]
Here is the file:
[jdk.nashorn.internal.scripts.Script$\^eval\_.class.zip](https://github.com/gmu-swe/phosphor/files/3249999/jdk.nashorn.internal.scripts.Script.eval._.class.zip)

Thanks!

**Comment by jon-bell** [comment]
Thanks for attaching this - it made this much easier to reproduce (and sorry for the delay, last week was full of travel). Let me know if you run into any more issues (I didn't try to run OpenMRS with the same JDK).

**Comment by goatgoose1142** [comment]
Thanks so much!

That error message is gone now. However, OpenMRS still hangs forever when it reaches that same part in the log. I could try switching JDKs. Which one did you use?

**Comment by jon-bell** [comment]
I would suggest open jdk <=1.8_181

**Comment by goatgoose1142** [comment]
Ok I'll try that, thanks
