### ISSUE TITLE
What strategy does phosphor use for implicit flow detection? 

### ISSUE THREAD

**Issue by ivanpostolski** [gmu-swe/phosphor#131]
Hi 

I'm curious about the strategy that phosphor use for implicit flow detection (e.g permissive upgrade). For instance what would  phosphor return when tainting the following code snippet, for inputs  `x = true` or `x = false`

```
x = source(x);
y = true;
z = true;
     if(x)
         y = false;
    if(y)
         z = false
sink(z);

```

Cheers

**Comment by jon-bell** [comment]
The [implicit propagation integration tests](https://github.com/gmu-swe/phosphor/blob/master/Phosphor/test/edu/columbia/cs/psl/test/phosphor/GeneralImplicitITCase.java) contain examples that demonstrate the expected propagations.

Assuming that your snippet is run with control tracking mode enabled, and also with branch-not-taken enabled (which is on by default when control tracking is turned on), `y` and `z` would both always receive `x`'s taint mark. When running with control tracking but without branch-not-taken, `y` would receive `x`'s mark only if `x = true`, and `z` would never receive the mark. 

We are very actively working on implementing new techniques for implicit flow detection and measuring their relative precision/recall on different tasks. For now, the best reference (aside from the tests) is [our ISSTA 2015 demo paper](http://mice.cs.columbia.edu/getTechreport.php?techreportID=1601).

**Comment by ivanpostolski** [comment]
Hello Jonathan.

Thanks! Great references. Which corpus /benchmark/testing do you use for
measuring precision/recall of the techniques?

**Comment by jon-bell** [comment]
We could not find any existing benchmarks, and hence are building our own, but would be open to any suggestions.

**Comment by jon-bell** [comment]
Feel free to continue this discussion, but I don't think it's an issue at this point so will close it.
