### ISSUE TITLE
Phosphor instrumentation affects method parameter visibility

### ISSUE THREAD

**Issue by strb** [gmu-swe/phosphor#132]
For some methods where phosphor injects local variables and initialization code at the start of the method, the visibility range of the method's parameters is pushed back, making them only accessible after the injected instrumentation code has run. 

This causes problems when running phosphor-instrumented code in a debugger, because it can cause method parameters not to be visible upon method entry.

Here's an example. After instrumentation, the method with this signature:

````
static void escape(String s, StringBuffer sb) 
````

has the following bytecode prepended to it:

````
       0: new           #211                // class edu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag
       3: dup
       4: invokespecial #212                // Method edu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag."<init>":()V
       7: astore_2
       8: new           #214                // class edu/columbia/cs/psl/phosphor/struct/TaintedCharWithObjTag
      11: dup
      12: invokespecial #215                // Method edu/columbia/cs/psl/phosphor/struct/TaintedCharWithObjTag."<init>":()V
      15: astore_3
````

The LocalVariableTable then looks like this:

```
Start  Length  Slot  Name   Signature
  282      30     6     k   I
   55     286     9 ch$$PHOSPHORTAG   Ledu/columbia/cs/psl/phosphor/runtime/Taint;
    8     333     3 phosphorReturnPreAlloc1   Ledu/columbia/cs/psl/phosphor/struct/TaintedCharWithObjTag;
    0     341     2 phosphorReturnPreAlloc0   Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag;
   18     323     5 i$$PHOSPHORTAG   Ledu/columbia/cs/psl/phosphor/runtime/Taint;
  272      50     7    ss   Ljava/lang/String;
   62     272     8    ch   C
   25     315     4     i   I
   16     325     0     s   Ljava/lang/String;
   16     325     1    sb   Ljava/lang/StringBuffer;
````
As you can see from the offsets, the two parameters `s` and `sb` are only visible after the setup instructions have executed.

It looks to me like the local variable management/sorting in ASM could be the culprit, but I'm not well versed enough in this to more precisely diagnose or fix the issue myself. If you need any more information from me, let me know. Thanks for taking a look.

**Comment by jon-bell** [comment]
I think that what I just pushed should catch all of the cases of this happening - but give it a try and let me know.
