### ISSUE TITLE
SpongeForge java.lang.IllegalAccessException

### ISSUE THREAD

**Issue by ZangeloRaj** [gmu-swe/phosphor#143]
I'm running a Sponge server and after starting the server, I get this error and Phosphor tells me to put this in the issue tracker. Here is the [**log**](https://pastebin.com/BzsgbvJ4).
I'm running Phosphor 1.12.2 0.2.6 Build 50 and SpongeForge 1.12.2-2838-7.2.1-RC4010.
Should I disable this in the config or is this something I should act upon?

**Comment by jon-bell** [comment]
Hi, I’m sorry - I think that you have found the wrong “Phosphor” project. This project is a dynamic data flow analysis engine. Is it possible that you have the wrong issue tracker here?

**Comment by ZangeloRaj** [comment]
Oh apologies! It was the wrong Phosphor. Sorry for posting here.
