### ISSUE TITLE
enhancement of BlockList in Phosphor

### ISSUE THREAD

**Issue by coder-chenzhi** [gmu-swe/phosphor#153]
This issue is not a bug but the enhancement for Phosphor. We want to skip the instrumentation for certain classes and packages via BlockList for two reasons: (1) **avoiding performance issues**. We find that the size of instrumented jar files is about x10 times of the original size, and the final size is over 1GB for some complex projects; (2) **avoiding compatible issues**. There are too many third-party libraries in SpringBoot applications. The dynamic language features of Java (such as reflection, lambda, and instrumentation) are likely used in these libraries, which increase the risk of incompatibility with Phosphor. Therefore, we think it is quite reasonable to implement BlockList in practice.

**We have tried to achieve this via `Instrumentor.isIgnoredClass()` in Phosphor.** However, we find that this function is not working as we imaging. When rewriting the method calls, Phosphor will check whether the owner classes of the method are ignored. If the owner classes are ignored, the method calls will keep unchanged. Otherwise, they will be replaced with the calls to wrapper methods. However, the owner classes are the classes used to make the method calls at compile-time, and the actual class used at runtime may be the subtypes of owner classes. Moreover, the instrumentation status of the owner classes and actual classes may not be the same. For example, if the owner class is not ignored and the actual class is ignored, the method call is rewritten to invoke the wrapper method, which is nonexistent in the actual class, and exception throws.

Do you have any idea to implement this feature?

## How to reproduce
To repoduce this issue, you need to
- create a maven projects with following code and pom.xml
- build the fat jar
- chaneg the source code of Phosphor to add a new ignored class in `Instrumentor.isIgnoredClass()`
- build Phosphor
- instrument the fat jar with Phosphor
- run the instrumented fat jar with Phosphor

`MyComparator.java`
```
package com.example.test.ignored;

import java.util.Comparator;

public class MyComparator implements Comparator<Integer> {

    @Override
    public int compare(Integer o1, Integer o2) {
        return o1 - o2;
    }
}
```

`Inst2Uninst.java`
```
package com.example.test;

import com.example.test.ignored.MyComparator;

import java.util.Arrays;
import java.util.Comparator;

public class Inst2Uninst {

    public static void main(String[] args) {
        Comparator<Integer> comparator = new MyComparator();
        Integer[] arr = {9, 8, 7, 6, 5, 4, 3, 2, 1};
        Arrays.sort(arr, comparator);
        for (int i : arr) {
            System.out.println(i);
        }
    }
}
```

`pom.xml`
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>inst2uninst-reproduce</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.1.0</version>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
            </plugin>
            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.0.2</version>
            </plugin>
            <!-- Maven Shade Plugin -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.3</version>
                <executions>
                    <!-- Run shade goal on package phase -->
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <!-- add Main-Class to manifest file -->
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>com.example.test.Inst2Uninst</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

The patch to Phosphor
```
diff --git a/Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/Instrumenter.java b/Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/Instrumenter.java
index 126cd4cb..2f8b242d 100644
--- a/Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/Instrumenter.java
+++ b/Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/Instrumenter.java
@@ -124,7 +124,8 @@ public class Instrumenter {
                 || StringUtils.startsWith(owner, "java/lang/invoke/LambdaForm")
                 || StringUtils.startsWith(owner, "java/lang/invoke/LambdaMetafactory")
                 || StringUtils.startsWith(owner, "edu/columbia/cs/psl/phosphor/struct/TaintedWith")
-                || StringUtils.startsWith(owner, "java/util/regex/HashDecompositions"); //Huge constant array/hashmap
+                || StringUtils.startsWith(owner, "java/util/regex/HashDecompositions") //Huge constant array/hashmap
+                || StringUtils.startsWith(owner, "com/example/test/ignored");
     }

     public static void analyzeClass(InputStream is) {
```

## The stack trace of exception
We can see that the `Inst2Uninst.main` call the `com/example/test/ignored/MyComparator.compare$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/runtime/Taint;Ljava/lang/Object;Ledu/columbia/cs/psl/phosphor/runtime/Taint
;Ljava/lang/Object;Ledu/columbia/cs/psl/phosphor/runtime/Taint;Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag;)Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag;` of `MyComparator`. However, `MyComparator` is ignored without instrumentation, so the tainted methods is nonexistent.
```
Exception in thread "main" java.lang.AbstractMethodError: Method com/example/test/ignored/MyComparator.compare$$PHOSPHORTAGGED(Ledu/columbia/cs/psl/phosphor/runtime/Taint;Ljava/lang/Object;Ledu/columbia/cs/psl/phosphor/runtime/Taint
;Ljava/lang/Object;Ledu/columbia/cs/psl/phosphor/runtime/Taint;Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag;)Ledu/columbia/cs/psl/phosphor/struct/TaintedIntWithObjTag; is abstract
        at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java)
        at java.lang.Throwable.fillInStackTrace$$PHOSPHORTAGGED(Throwable.java:784)
        at java.lang.Throwable.<init>(Throwable.java:266)
        at java.lang.Error.<init>(Error.java:70)
        at java.lang.LinkageError.<init>(LinkageError.java:55)
        at java.lang.IncompatibleClassChangeError.<init>(IncompatibleClassChangeError.java:55)
        at java.lang.AbstractMethodError.<init>(AbstractMethodError.java:56)
        at java.lang.AbstractMethodError.<init>(AbstractMethodError.java)
        at com.example.test.ignored.MyComparator.compare$$PHOSPHORTAGGED(MyComparator.java)
        at java.util.TimSort.countRunAndMakeAscending$$PHOSPHORTAGGED(TimSort.java:355)
        at java.util.TimSort.sort$$PHOSPHORTAGGED(TimSort.java:220)
        at java.util.Arrays.sort$$PHOSPHORTAGGED(Arrays.java:1438)
        at com.example.test.Inst2Uninst.main$$PHOSPHORTAGGED(Inst2Uninst.java:14)
        at com.example.test.Inst2Uninst.main(Inst2Uninst.java)
```

**Comment by jon-bell** [comment]
Phosphor's "block list" of classes are classes that are not instrumented *at all*. This level of exclusion is only possible on certain classes, since for instance, if the class that you want to "not instrument" reads an array field of another object (which is instrumented), it will crash since the field type is not the expected type. Similarly, as you found, this can cause AbstractMethodErrors due to some classes in the hierarchy being instrumented and others not instrumented. I would suggest coming at the problem from a different direction: is the problem that you are trying to solve bugs in reflection, bugs in lambdas, or incompatibility with other instrumentation engines?

**Comment by coder-chenzhi** [comment]
Thanks, Jon. The problem is that there are lots of third-party libraries dependent by SpringBoot applications. We feel that it is likely to conflict with Phosphor, and we need to spend lots of time to figure out and solve these problems. Therefore, we'd like to **find other workaround to skip these problems**.  

If there are no possible solutions for this feature , we will follow your suggestion to go on to solve the real problems in Phosphor.

**Comment by jon-bell** [comment]
It's hard for me to speculate on whether it's possible to truly remove Phosphor's instrumentation from large components of your application. If you think that it might be easier than fixing the underlying causes of the incompatibility, you can take a look at `UninstrumentedCompatMV` for a sketch of what minimal instrumentation would look like - but please note that this is not really the intended use case for that method visitor, and you may run into more problems than it's worth to keep going down the path of ignoring some methods.
