### ISSUE TITLE
NullpointerException in TaintSourceWrapper.getStringValueTaints

### ISSUE THREAD

**Issue by Icysandwich** [gmu-swe/phosphor#156]
getStringValueTag can return null. In getStringValueTaints, return getStringValueTag.taints can be null.taints, which throw a NPE.
Should make a check here.

**Comment by jon-bell** [comment]
Thanks for the find. Would you be able to prepare a pull request (with a patch and test case)?

**Comment by Icysandwich** [comment]
PR submitted. #157

**Comment by jon-bell** [comment]
Thank you for the contribution!
