### ISSUE TITLE
A verify error occurs when auto-taint.

### ISSUE THREAD

**Issue by Icysandwich** [gmu-swe/phosphor#158]
I meet a wired bug when auto taint a source method.
A VerifyError occurs when meets 3 requirements:
1. The method is the source method.
2. The method body has a loop.
3. The method returns a String.

A convenient way to reproduce this bug is to add a loop in _source_() method in AutoTaintObjTagITCase:
```java
	public String source() {
		for(int j=0;  j<1; j++) {};
		return "Foo";
	}
```
During the mvn verify task, the error occurs.

**Comment by Icysandwich** [comment]
It seems that there are some conflicts between Phosphor's instrumentation and autotaint's instrumentation, i.e., something wrong in SourceTaintingMV. 
Just a guess.

**Comment by Icysandwich** [comment]
I look into SourceTaintingMV and feel confused about the instrumentation logic.
Why instrumenting all arguments twice rather than simply instrumenting the return value?

**Comment by Icysandwich** [comment]
The stack map table of source() seems wired:
```
      Stack map table: number of frames 2
        [pc: 65, full, stack: {}, locals: {com.dongwang.Example, edu.columbia.cs.psl.phosphor.runtime.Taint, edu.columbia.cs.psl.phosphor.struct.TaintedReferenceWithObjTag, _, int, edu.columbia.cs.psl.phosphor.runtime.Taint}]
        [pc: 68, same]
```
Maybe it is the root cause.
Trying to figure out how it occurs.

**Comment by jon-bell** [comment]
FYI, I debugged this by using a fastdebug enabled JVM, and using `-XX:+TraceExceptions -XX:+VerboseVerification` - this revealed the invalid variable access in the auto taint code, now fixed.
