### ISSUE TITLE
ClassCastException in TaintLoadCoercer

### ISSUE THREAD

**Issue by Icysandwich** [gmu-swe/phosphor#161]
Line 204 in TaintLoadCoercer.class
`this.instructions.insertBefore(insn, new TypeInsnNode(CHECKCAST, wrappedType.getInternalName()));`
throws a ClassCastException.

The whole block:
```
((FieldInsnNode) insn).desc = wrappedType.getDescriptor();
this.instructions.insertBefore(insn, new MethodInsnNode(Opcodes.INVOKESTATIC, Type.getInternalName(MultiDTaintedArray.class), "boxIfNecessary", "(Ljava/lang/Object;)Ljava/lang/Object;", false));
this.instructions.insertBefore(insn, new TypeInsnNode(CHECKCAST, wrappedType.getInternalName()));
```

In my test case, _insn_ here is a multi dimension primitive array double[][].
_wrappedType_ got by _MultiDTaintedArrayWithObjTag.getTypeForType_ is a LazyReferenceArrayObjTags, while the above _boxIfNecessary_ method returns a _[LazyDoubleArrayObjTags_. So the checkcast fail.

**Comment by Icysandwich** [comment]
It is inconsistent for the wrapper of a multi dimension array. Sometimes it is a [Lazy***ArrayObjTags (*** is the corresponding primitive type), but it can directly be a LazyReferenceArrayObjTags in some cases. Which one is correct?

**Comment by jon-bell** [comment]
Multi-dimensional primitive arrays should now always be a `LazyReferenceArrayObjTags`
