### ISSUE TITLE
Wrong class context when applying phosphor

### ISSUE THREAD

**Issue by Icysandwich** [gmu-swe/phosphor#165]
I use SecurityManager to get the class context in my code:
```java
Class<?>[] context = new SecurityManager() {
     @Override
     public Class<?>[] getClassContext() {
           return super.getClassContext();
     }
}.getClassContext();
```

Without phosphor applied, the ```context``` array has two elements:
```
phosphortest.Main$1
phosphortest.Main
```

After phosphor applied, the array elements changed:
```
java.lang.SecurityManager
phosphortest.Main$1
phosphortest.Main
phosphortest.Main
```

FYI, I write a demo on [my test repo](https://github.com/Icysandwich/phosphortest). 
Use ```mvn package``` to build a runnable jar first, and run the jar without Phosphor 
```bash
java -jar smtest-0.0.1-SNAPSHOT-jar-with-dependencies.jar
```
and with Phosphor
```bash
java -Xbootclasspath/a:Phosphor-0.0.5-SNAPSHOT.jar -javaagent:Phosphor-0.0.5-SNAPSHOT.jar -cp smtest-0.0.1-SNAPSHOT-jar-with-dependencies.jar phosphortest.Main
```
respectively. You can find the above console output.

**Comment by jon-bell** [comment]
Can you describe a little bit more about the use case that requires this to be masked? `getClassContext` is intended to return an entry for each active stack frame, and there are, in fact, more active stack frames when running with Phosphor than without. Is it obligatory that *all* extra stack frames are removed, or would it be sufficient just to chop off the false first entry (`java.lang.SecurityManager`)?

**Comment by Icysandwich** [comment]
This case is still in JNA.
https://github.com/java-native-access/jna/blob/a0641dd928776a8e81478015a1f14a39326887f3/src/com/sun/jna/Native.java#L1503-L1517

The return value ```context[3]``` is the class which native methods located in. When JNA runs with Phosphor, the value of ```context[3]``` will be class ```Native``` itself.

**Comment by Icysandwich** [comment]
This case is still in JNA.
Please see:
https://github.com/java-native-access/jna/blob/a0641dd928776a8e81478015a1f14a39326887f3/src/com/sun/jna/Native.java#L1503-L1517

The return value ```context[3]``` is the class which native methods located in. When JNA runs with Phosphor, the value of ```context[3]``` will be class ```Native``` itself.

**Comment by jon-bell** [comment]
I see. Do you think that this is the only place that this comes up? Basically, the two options are:
1. Patch `getCallingClass` to return the actual calling class
2. Patch `getClassContext` to mask all Phosphor-related stack frames.

I'm leaning towards option #1.

**Comment by Icysandwich** [comment]
Yes so far I only meet this case here. And I also agree that  it is not graceful that ```getCallingClass``` uses a fixed index to get the class.
But on the other hand, maybe it is still a bug for Phosphor? Since Phosphor is an anlysis tool, it should not affect the execution result of the target program. I mean, adding extra frames. 
I'm not really sure.

**Comment by jon-bell** [comment]
Does 0ea5afd fix this for you?

**Comment by Icysandwich** [comment]
Yes it does. Issue closed. 
(But I still think there may exist a more perfect solution.)
