### ISSUE TITLE
`taintedReference` has a different behaviour than `taintedObject` for taint tracking on Strings

### ISSUE THREAD

**Issue by thakkarparth007** [gmu-swe/phosphor#167]
As per #138, the new way to taint objects is to use `taintedReference` instead of `taintedObject`. This causes issues when dealing with Strings (and I'm mostly dealing with Strings). I've reproduced the exact behaviour in the following tests:

TLDR: when using `taintedObject`, a string derived from a tainted string (via concatenation) is correctly marked as tainted (both under data flow tracking and control flow tracking). However, when using `taintedReference`, the derived string is not marked tainted under data flow tracking (but it retains the taint under control flow tracking).

Also, behaviour of MultiTainter.getTaints is slightly unintuitive for Strings. Currently I figured out the way to check if a string is tainted by looking at some code in Phosphor (I think from some AutoTaint related code). As the code below shows, a string itself isn't marked tainted even though its characters are marked tainted. Now this might be a design decision, but I just thought I'd let you know that it feels a little unintuitive, and there should perhaps be some helper methods to get taints of "children" of an object/array.

```java
class PhosphorStringTests {
    @Test
    void test4_data() {
        String foo1 = "hello world";
        MultiTainter.taintedObject(foo1, Taint.withLabel("taint1"));

        String foo2 = "hell, o world?";
        foo2 = MultiTainter.taintedReference(foo2, "taint2");

        // direct string taint testing
        System.out.println(MultiTainter.getTaint(foo1) + " " + getTaintLabels(foo1) + " " + isStringTainted(foo1));
        System.out.println(MultiTainter.getTaint(foo2) + " " + getTaintLabels(foo2) + " " + isStringTainted(foo2));

        assert MultiTainter.getTaint(foo1).isEmpty() == true;
        assert getTaintLabels(foo1).size() == 1;
        assert isStringTainted(foo1) == true;

        assert MultiTainter.getTaint(foo2).isEmpty() == false;        
        assert getTaintLabels(foo2).size() == 1;
        assert isStringTainted(foo2) == true;

        // derived string taint testing
        String bar1 = foo1 + "!";
        String bar2 = foo2 + "!";

        System.out.println(MultiTainter.getTaint(bar1) + " " + getTaintLabels(bar1) + " " + isStringTainted(bar1));
        System.out.println(MultiTainter.getTaint(bar2) + " " + getTaintLabels(bar2) + " " + isStringTainted(bar2));

        // Using taintedObject - taint is propagated correctly.
        assert MultiTainter.getTaint(bar1).isEmpty() == true;
        assert getTaintLabels(bar1).size() == 1;
        assert isStringTainted(bar1) == true;

        // Using taintedReference - taint is not propagated (via all means of looking for the taint)!
        // this is under data flow tracking
        assert MultiTainter.getTaint(bar2).isEmpty() == true;        
        assert getTaintLabels(bar2).size() == 0;
        assert isStringTainted(bar2) == false;
    }

    @Test
    void test4_ctrl() {
        String foo1 = "hello world";
        MultiTainter.taintedObject(foo1, Taint.withLabel("taint1"));

        String foo2 = "hell, o world?";
        foo2 = MultiTainter.taintedReference(foo2, "taint2");

        // direct string taint testing
        System.out.println(MultiTainter.getTaint(foo1) + " " + getTaintLabels(foo1) + " " + isStringTainted(foo1));
        System.out.println(MultiTainter.getTaint(foo2) + " " + getTaintLabels(foo2) + " " + isStringTainted(foo2));

        assert MultiTainter.getTaint(foo1).isEmpty() == true;
        assert getTaintLabels(foo1).size() == 1;
        assert isStringTainted(foo1) == true;

        assert MultiTainter.getTaint(foo2).isEmpty() == false;        
        assert getTaintLabels(foo2).size() == 1;
        assert isStringTainted(foo2) == true;

        // derived string taint testing
        String bar1 = foo1 + "!";
        String bar2 = foo2 + "!";

        System.out.println(MultiTainter.getTaint(bar1) + " " + getTaintLabels(bar1) + " " + isStringTainted(bar1));
        System.out.println(MultiTainter.getTaint(bar2) + " " + getTaintLabels(bar2) + " " + isStringTainted(bar2));

        // Using taintedObject - taint is propagated correctly.
        assert MultiTainter.getTaint(bar1).isEmpty() == true;
        assert getTaintLabels(bar1).size() == 1;
        assert isStringTainted(bar1) == true;

        // Using taintedReference - taint is propagated correctly (this is under control flow tracking).
        assert MultiTainter.getTaint(bar2).isEmpty() == true;        
        assert getTaintLabels(bar2).size() == 1;
        assert isStringTainted(bar2) == true;
    }

    boolean isStringTainted(String s) {
        return getTaintLabels(s).size() > 0;
    }

    HashSet<Object> getTaintLabels(String s) {
        HashSet<Object> labels = new HashSet<Object>();
        for (int i = 0; i < s.length(); i++) {
            Object[] lbls = MultiTainter.getTaint(s.charAt(i)).getLabels();
            if (lbls != null) {
                for (int j = 0; j < lbls.length; j++) {
                    labels.add(lbls[j]);
                }
            }
        }
        return labels;
    }
}
```

**Comment by thakkarparth007** [comment]
Btw, this does not happen for `Integer.parseInt(myString) + someOtherString`, which is pretty strange.

```java
    @Test
    void test5_data() throws Exception {
        String foo1 = "59";
        MultiTainter.taintedObject(foo1, Taint.withLabel("taint1"));

        String foo2 = "79";
        foo2 = MultiTainter.taintedReference(foo2, "taint2");

        // direct string taint testing
        System.out.println(MultiTainter.getTaint(foo1) + " " + getTaintLabels(foo1) + " " + isStringTainted(foo1));
        System.out.println(MultiTainter.getTaint(foo2) + " " + getTaintLabels(foo2) + " " + isStringTainted(foo2));

        assert MultiTainter.getTaint(foo1).isEmpty() == true;
        assert getTaintLabels(foo1).size() == 1;
        assert isStringTainted(foo1) == true;

        assert MultiTainter.getTaint(foo2).isEmpty() == false;        
        assert getTaintLabels(foo2).size() == 1;
        assert isStringTainted(foo2) == true;

        // derived string taint testing
        String bar1 = Integer.parseInt(foo1) + "1";
        String bar2 = Integer.parseInt(foo2) + "2";

        System.out.println(MultiTainter.getTaint(bar1) + " " + getTaintLabels(bar1) + " " + isStringTainted(bar1));
        System.out.println(MultiTainter.getTaint(bar2) + " " + getTaintLabels(bar2) + " " + isStringTainted(bar2));

        // Using taintedObject - taint is propagated correctly.
        assert MultiTainter.getTaint(bar1).isEmpty() == true;
        assert getTaintLabels(bar1).size() == 1;
        assert isStringTainted(bar1) == true;

        // Using taintedReference - taint is propagated correctly.
        assert MultiTainter.getTaint(bar2).isEmpty() == true;        
        assert getTaintLabels(bar2).size() == 1;
        assert isStringTainted(bar2) == true;
    }
```

**Comment by jon-bell** [comment]
The original string tainting behavior in Phosphor was something of a work-around, before we had reference tainting. Without reference tainting, it was not possible to distinguish between the taint of a reference to a string, and the taint on a string's characters. Now, with reference tainting (and `taintedReference`), that distinction becomes possible. As we found when [evaluating the precision of different control-flow propagation policies](https://jonbell.net/publications/conflux), over-eagerly propagating taint tags from references to strings to all of the characters in that string can cause imprecise results for applications that expect that this precision is maintained.

The current design assumes that clients of the Phosphor API that care for special handling of String taints will implement that special handling directly, while Phosphor will continue to propagate reference taints separately from character taints - it is still the case that Phosphor will propagate taint tags on characters, if they are tainted. But, in the case of:

```
foo2 = MultiTainter.taintedReference(foo2, "taint2");
```

This literally means that `foo2` is a tainted reference to the value that `foo2` pointed to. It will not taint the characters of the string. This is important for API clients that care about this distinction.

`Integer.parseInt(someInt)` is still handled as a special case that will propagate the taint tags of a string into an integer, and then calling toString will still propagate it back to that string.

I hope that this helps to understand the current behavior. I agree that these semantics are poorly (if at all) documented, and there may be some bugs (either in the implementation, or in the intended behavior). If you would like to share more information about your use case for Phosphor, I might be able to help point you into the right direction.

**Comment by thakkarparth007** [comment]
Thanks for the detailed response! This makes it quite clear as to what's happening. I have two follow-up questions:

1. My use case is okay with slightly over approximated taint propagation. The taint sources are largely strings, and as per this explanation, I can taint the individual characters. However, I've ended up going back to taintedObject for now and that seems to be working as I'd like it to. If I'm okay with over-approximation, this should be an okay choice, right?

2. Minor: Is the `Integer.parseInt` behavior "correct" if it's passed a tainted reference to a string? Specifically, are there plans to change that in a future release? Asking only for documenting the intention/behavior here!

Btw (this is another but related issue, so I can create a new thread if you'd like), it'd be very nice if there was a way to customize the taint propagation logic. For example, in my use case, I want to taint a string (e.g., a file name), and if a `java.io.File` object is created from that tainted name, I want all data read from the file to be tainted as well. Currently this doesn't happen automatically. In fact, even the File object isn't tainted as well (because of the focus on precision). For this, I'm doing my own instrumentation and adding my own taint propagation rules using Soot. That seems to work okay for me because I get to work with a higher level Jimple model of source code instead of JVM bytecode, but is also quite slow. I also don't know how to extend Phosphor's taint propagation rules (I tried looking through the source code but it'd take some time to understand the code without docs).

The ability to encode custom taint propagation rules (or if already possible, then documentation of such an ability) would be fantastic. Phosphor already offers a course grained control over different taint propagation policies, but I'm asking for a finer grained control. Phosphor's already the best solution I know of when it comes to taint _tracking_, but if taint _propagation_ was made customizable, then it'd be a one stop shop for anything taint related.

**Comment by jon-bell** [comment]
> My use case is okay with slightly over approximated taint propagation. The taint sources are largely strings, and as per this explanation, I can taint the individual characters. However, I've ended up going back to taintedObject for now and that seems to be working as I'd like it to. If I'm okay with over-approximation, this should be an okay choice, right?

That sounds OK.

> Minor: Is the Integer.parseInt behavior "correct" if it's passed a tainted reference to a string? Specifically, are there plans to change that in a future release? Asking only for documenting the intention/behavior here!

We have no plans to change this in a future release, but if you would like to propose a PR that changes its behavior and/or documentation, I would be happy to review it.

> The ability to encode custom taint propagation rules (or if already possible, then documentation of such an ability) would be fantastic. Phosphor already offers a course grained control over different taint propagation policies, but I'm asking for a finer grained control. Phosphor's already the best solution I know of when it comes to taint tracking, but if taint propagation was made customizable, then it'd be a one stop shop for anything taint related.

Thanks! It does indeed allow for full customization of the taint propagation policy by providing a custom implementation of `TaintTagFactory`. It is not very well documented, and modifying this behavior certainly will require some additional knowledge of Bytecode instrumentation. One example customization is in our project [knarr](https://github.com/gmu-swe/knarr), which uses Phosphor to track constraints through its [PathConstraintTagFactory](https://github.com/gmu-swe/knarr/blob/master/knarr/src/main/java/edu/gmu/swe/knarr/runtime/PathConstraintTagFactory.java). We also have a higher-level abstraction, the [ControlFlowPropagationPolicy](https://github.com/gmu-swe/phosphor/blob/master/Phosphor/src/main/java/edu/columbia/cs/psl/phosphor/control/ControlFlowPropagationPolicy.java), which might be the easiest abstraction to use if you would like to retain Phosphor's existing dataflow propagation rules, and primarily modify the control flow rules.

Outside of this issue, I am happy to chat more about how to achieve your goals with Phosphor and assist with the less-documented aspects; particularly in the hopes that you might be able to transfer some of that knowledge into documentation :)

**Comment by thakkarparth007** [comment]
Thanks for the confirmation and the pointers! I took a look at PathConstraintTagFactory (and then a bit through TaintPassingVM + DataAndControlFlowTagFactory which seem to contain the bulk of the propagation logic). I think I have a very high level idea of how things work now, so thanks for the pointers! Currently though, my workflow of using soot is working just enough for my use case - it's a bit slow to instrument, but gives me higher level semantics I'm familiar with. In case I do need to work at bytecode level for more instrumentation, I will definitely take you up on the offer! :)

I'd have loved to help out with the documentation but currently I already have more than enough on my plate, so I'm hesitant to commit to more work. But I might reach out some time in future if/when I take up a fuzzing-related project.

Thanks for your help!
