### ISSUE TITLE
mvn package

### ISSUE THREAD

**Issue by 12089897411** [gmu-swe/phosphor#180]
Hi,
When I execute the MVN package, I find an error  like this： Cannot resolve plugin edu.gmu.swe.phosphor:phosphor-instrument-maven-plugin:0.1.0-SNAPSHOT

**Comment by jon-bell** [comment]
Are there any other errors that occur before that one? It would be helpful to hear more information about exactly what you are running (the environment and the command) and what you are seeing. Please note that I am still seeing passing behavior on `mvn install` in our CI workflow - https://github.com/gmu-swe/phosphor/actions/runs/2911505293

**Comment by 12089897411** [comment]
Hi,@jon-bell 

No other errors appear, after downloading from git, I use Intellij IDEA to open,  this error occurs.

**Comment by jon-bell** [comment]
@12089897411 It would be helpful to hear more information about exactly what you are running (the environment and the command) and what you are seeing. Please copy and paste the entire text output of running the command `mvn install` after downloading it from git and before opening it in IntelliJ.

**Comment by 12089897411** [comment]
environment
System: windows10
JDK :11
idea:2021
![image](https://user-images.githubusercontent.com/108512675/195757364-0495b63d-db7f-4bae-b7a4-3c357fff6ef8.png)

**Comment by jon-bell** [comment]
> Please copy and paste the entire text output of running the command mvn install after downloading it from git and before opening it in IntelliJ.
