### ISSUE TITLE
Embeded updated `Configuration` class into JDK?

### ISSUE THREAD

**Issue by aoli-al** [gmu-swe/phosphor#182]
Hi @jon-bell, 

I'm using `PRIOR_CLASS_VISITOR` and `POST_CLASS_VISITOR` to make some customized instrumentation. My workflow is 

- Create an instrumented JDK using `phosphor-instrument-jigsaw` with my prior/post class visitors
- Create an instrumented JAR file using `Phosphor` with my prior/post class visitors.
- Run instrumented JAR file with `phosphor-jigsaw-javaagent` and my prior/post class visitors

I'm having issues in step 3. While the `phosphor-jigsaw-javaagent` is initializing, some classes trigger the `MethodHandles$Lookup` method which calls `PreMain.instrumentClassBytes`. However, because this method is called before the javaagent is initialized, the Configuration is not set and my prior/post classes are not called. This causes some inconsistency between classes and leads to crashes. 

One execution path I found is (the line number is fabricated):

```
instrumentClassBytes:86, PreMain (edu.columbia.cs.psl.phosphor)
defineHiddenClass:222, MethodHandles$Lookup (java.lang.invoke)
generateInnerClass:222, InnerClassLambdaMetafactory (java.lang.invoke)
spinInnerClass:222, InnerClassLambdaMetafactory (java.lang.invoke)
buildCallSite:222, InnerClassLambdaMetafactory (java.lang.invoke)
metafactory:222, LambdaMetafactory (java.lang.invoke)
invokeStatic:-1, DirectMethodHandle$Holder (java.lang.invoke)
invokeExact_MT:-1, Invokers$Holder (java.lang.invoke)
invoke:222, BootstrapMethodInvoker (java.lang.invoke)
makeSite:222, CallSite (java.lang.invoke)
linkCallSiteImpl:222, MethodHandleNatives (java.lang.invoke)
linkCallSite:222, MethodHandleNatives (java.lang.invoke)
<clinit>:50055, JavaRuntimeURLConnection (sun.net.www.protocol.jrt)
openConnection:222, Handler (sun.net.www.protocol.jrt)
openConnection:222, URL (java.net)
openStream:222, URL (java.net)
getSystemResourceAsStream:222, ClassLoader (java.lang)
tryToAddClassNode:678, Instrumenter (edu.columbia.cs.psl.phosphor)
getClassNode:670, Instrumenter (edu.columbia.cs.psl.phosphor)
getAutoTaintMethods:260, BasicSourceSinkManager (edu.columbia.cs.psl.phosphor)
getAutoTaintMethods:265, BasicSourceSinkManager (edu.columbia.cs.psl.phosphor)
isSourceOrSinkOrTaintThrough:52, BasicSourceSinkManager (edu.columbia.cs.psl.phosphor)
retransform:110, SourceSinkTransformer (edu.columbia.cs.psl.phosphor)
<clinit>:-1, ArrayList$SubList (java.util)
subList:222, ArrayList (java.util)
split:222, String (java.lang)
split:222, String (java.lang)
parseArgs:64, PreMain (edu.columbia.cs.psl.phosphor)
premain:48, PreMain (edu.columbia.cs.psl.phosphor)
premain:40, PreMain (edu.columbia.cs.psl.jigsaw.phosphor.javaagent)
invoke0:-1, NativeMethodAccessorImpl (jdk.internal.reflect)
invoke:222, NativeMethodAccessorImpl (jdk.internal.reflect)
invoke:222, DelegatingMethodAccessorImpl (jdk.internal.reflect)
invoke:50567, Method (java.lang.reflect)
loadClassAndStartAgent:222, InstrumentationImpl (sun.instrument)
loadClassAndCallPremain:222, InstrumentationImpl (sun.instrument)
```

My current solution is to modify the `Configuration.java` to include prior/post class visitors. I'm trying to avoid this currently to make it work with upstream directly. (that's why I'm trying to patch back to Phosphor as much as possible 😊). 

Another solution I'm thinking of is to modify the Configuration class file before adding it to the JDK. I'm happy to submit a PR if you think this is the right design.

**Comment by jon-bell** [comment]
Yes, I think that it would make sense to inject values into the configuration class at instrumentation-time. I am not sure what the best API is here, though: presumably your class visitors need to be added to java.base also? I think that modifying the Configuration class file before adding it to the JDK is on the right track: there are already some similar hacks that occur in the jlink module - a PR would definitely be appreciated!

**Comment by jon-bell** [comment]
I'm sorry that this got dropped - the start of the semester is quite a busy time - I just merged in your PR.
