### ISSUE TITLE
What is the reason that this command cannot be executed under windows environment and the usage prompt pops up?

### ISSUE THREAD

**Issue by wangmanyou** [gmu-swe/phosphor#202]
java -jar phosphor-instrument-jigsaw-0.1.0-SNAPSHOT.jar C:\Program Files\Java\jdk-9.0.4 jre-inst
What is the reason that this command cannot be executed under windows environment and the usage prompt pops up?

**Comment by jon-bell** [comment]
Here is [an article describing why and how to escape spaces on command line prompts in windows](https://www.howtogeek.com/694949/how-to-escape-spaces-in-file-paths-on-the-windows-command-line/). If you have further questions, please be sure to copy-paste the entire command that you are running and the entire output to make it easier to diagnose/help.
