### ISSUE TITLE
Java Installation not found when executing mvn -pl :integration-tests verify.

### ISSUE THREAD

**Issue by HRsGIT** [gmu-swe/phosphor#215]
I am using JDK 17(I encountered the same issue on both JDK 9 and 11.) to compile Phosphor and the compilation was successful. However, when running the $mvn -pl :integration-tests verify$ command, I encountered the error shown in the image: 'Expected Java installation at: xxx'. Can you tell me why this is happening?
![image](https://github.com/user-attachments/assets/752e1c95-8d85-4721-be47-62b34a44cf4a)

![image](https://github.com/user-attachments/assets/39c5d42b-c61f-47f2-918e-dbfa339f75b4)

**Comment by jon-bell** [comment]
I'm sorry, but I do not have easy access to a WIndows machine to attempt to debug this. A user suggested a patch in #213 , but shared the patch as a screenshot which makes it more time consuming to merge in. I would suggest that you first try to get Phosphor working for your application in a Linux VM or container, and only then try to make it work in your Windows environment. If you run into further issues, please be certainy to copy and paste the complete log (text, not a screenshot) from following the installation steps.
