### ISSUE TITLE
Array Length Taint

### ISSUE THREAD

**Issue by chhokrad** [gmu-swe/phosphor#57]
Hi Jon

I have couple of questions :

1) I created an instrumented JRE with the following options -serialization -multiTaint -forceUnboxAcmpEq -withEnumsByValue -withArrayLengthTags -withArrayIndexTags. But I am unable to taint length of an array as shown in the example below
```java
public static void main(String[] args) throws Exception {
		int tainted_length = MultiTainter.taintedInt(3, "length_tainted");
		int[] array = new int[tainted_length];
		System.out.println(MultiTainter.getTaint(array.length));  // prints null
	}
```
2) Could you please give more information about these options -withoutFieldHiding  and -withSelectiveInst <arg> with the help of examples

**Comment by jon-bell** [comment]
These are experimental and unfinished options - I’m sorry that there is no documentation for them. You should not expect them to work - if they are things you are interested in, I can point you in the right direction to finish implementing them. 

Selective Instrumentation is designed to only do taint tracking in specific methods. I believe that field hiding is just for debugging and turns off some reflection masking stuff.

**Comment by chhokrad** [comment]
I am very much interested in Array length and index option. I would like to implement them, please point me in the right direction.

Sent from my iPhone

On Nov 30, 2017, at 10:04 AM, Jonathan Bell <notifications@github.com<mailto:notifications@github.com>> wrote:


These are experimental and unfinished options - I’m sorry that there is no documentation for them. You should not expect them to work - if they are things you are interested in, I can point you in the right direction to finish implementing them.

Selective Instrumentation is designed to only do taint tracking in specific methods. I believe that field hiding is just for debugging and turns off some reflection masking stuff.

**Comment by jon-bell** [comment]
OK. You should start by compiling and using the JVMTI agent (`-agentpath:JVMTIAgent/libphosphor.so`). Then, see what happens. It might just work. You can search for occurrences of the flag `edu.columbia.cs.psl.phosphor.Configuration.ARRAY_LENGTH_TRACKING` to see where I started implementing this - I think that it was mostly working at one point, but I haven't been testing/maintaining it as I as making other modifications.
