### ISSUE TITLE
The problem of "Can not do superclass..."

### ISSUE THREAD

**Issue by sonnguyenutd** [gmu-swe/phosphor#58]
Hello,
I have a question about Phosphor. 

My scenario is that I want to taint all methods' output in all classes by using Phosphor and ASM. Your tool works perfectly with my sample projects. However, when I try to work with a version of joda-time (extracted from Defects4J), I've found that there are some `ClassNotFoundException` issues. These issues occur when `edu.columbia.cs.psl.phosphor.org.objectweb.asm.ClassWriter.getCommonSuperClass` tries to get the common super class of 2 classes, but `getClass` (in `edu.columbia.cs.psl.phosphor.PreMain$PCLoggingTransformer$HackyClassWriter`) can not find at least one of them. A example: `Can not do superclass for org/joda/time/DateTimeZone and org/joda/time/tz/FixedDateTimeZone`

So, is that a bug? If so, is there any solution for that?

**Comment by jon-bell** [comment]
Hi,
Are you using the most recent version of Phosphor? I don't think that this message has existed for some time.

**Comment by sonnguyenutd** [comment]
I am using the most recent version, but I found that methods in some classes are not instrumented, then I modified your `Premain.java` by adding a try catch like that:
FROM
`public byte[] transform(ClassLoader loader, final String className2, Class<?> classBeingRedefined,
				ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
			byte[] ret = _transform(loader, className2, classBeingRedefined, protectionDomain, classfileBuffer);
			return ret;
		}`
TO
`public byte[] transform(ClassLoader loader, final String className2, Class<?> classBeingRedefined,
				ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
			byte[] ret = null;
			try {
				ret = _transform(loader, className2, classBeingRedefined, protectionDomain, classfileBuffer);
			} catch (Exception e) {
				e.printStackTrace();
			}
			return ret;
		}`
I tried to find why the exception exists, so I uncommented lines 80-81 in Premain.java and the message `Can not do superclass...` is shown.

So, is it true that if a class can not be found, it would not be transformed (in this case)?

**Comment by jon-bell** [comment]
Maybe you can provide a stack trace?

**Comment by sonnguyenutd** [comment]
I tried to run maven test in joda-time project with Phosphor, so I set up surefire's configuration arguments such as jvm and argLine (jvm is `jre-inst-obj/bin/java` and argLine is classpath + javaagent).
In order to taint methods' output, I override ASM's `MethodVisitor` and put into Premain.java right before line 164. I found that methods in some classes are not tainted.

**Comment by jon-bell** [comment]
@sonnguyenutd  Please answer the following precisely:

1. What is not being instrumented?
2. Is an exception actually being caught in transform? If so, please provide the stack trace.

I do not know what "put into Premain.java right before line 164" means.

**Comment by sonnguyenutd** [comment]
1. I mean the bytecode of some classes
2. No. Sorry! 
I might understand incorrectly your tool. Sorry about that! You can close this issue.
Thanks,

**Comment by jon-bell** [comment]
>I mean the bytecode of some classes

I need you to tell me _which_ classes and _why_ you suspect they are not instrumented. How can I reproduce what you are seeing? When I do reproduce it, how can I understand that the behavior is wrong?

**Comment by sonnguyenutd** [comment]
In this case, I might understand incorrectly and incompletely Phosphor!
WHY. In my problem, I try to modify classes to taint methods' output. I construct my own Java Agent and run along with Phosphor, but I can't run maven test with an argument having 2 agents (argLine of maven surefire, `UnsupportedOperationException`). So I decided to modify classes right before they are transformed in Phosphor:
`
public byte[] transform(ClassLoader loader, final String className2, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
	try {
		ClassReader cr = new ClassReader(classfileBuffer);
		ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES);
		ClassCollector ca = new ClassCollector(cw);
		cr.accept(ca, 0);
		classfileBuffer = cw.toByteArray();
	} catch (Exception e) {
		e.printStackTrace();
	}
	byte[] ret = _transform(loader, className2, classBeingRedefined, protectionDomain, classfileBuffer);

	return ret;
}
`
There are some classes that are not modified by the code I added. I though that your tool has a bug, but that is not true. Because you overrode `getCommonSuperClass` for your purpose (like you explained).

I hope you understand that reason! Do you still want to reproduce what I am seeing?

**Comment by jon-bell** [comment]
OK - so, it sounds like the problem is in your own instrumentation, and not at all in Phosphor? You can absolutely run multiple java agents with Maven Surefire. I would strongly recommend that you do it like that. Note that you will need to use the TaintedByteArrayWithObjTags transform$$PHOSPHORTAGGED signature, rather than just the byte[] one for it to work.

**Comment by sonnguyenutd** [comment]
You are right!
Thank you for recommending me!
