### ISSUE TITLE
String contains fails to produce taint results.

### ISSUE THREAD

**Issue by qorost** [gmu-swe/phosphor#59]
Hi Jon,

I found phosphos can't handle string operations properly. Here is my code:
```
public static void testString(String x) 
{
        MultiTainter.taintedObject(x, new Taint("string x"));
        boolean a = x.contains("a");
        Taint t = MultiTainter.getTaint(a);
        if(t != null)
            System.out.println("taint for a is " + t.toString());
}
```
Phosphos fails on getTaint for `a`. 

Environment:
I am using phosphor-0.0.3 on ubuntu 17.04.

**Comment by jon-bell** [comment]
"Contains" links its return value with the input string only through control flow, not through direct data flow. Phosphor does not special case String operations to manually propagate such marks, but it trivially could. In the implicit tracking mode, `a` would be tainted (regardless of whether the string contains 'a' or not), please see the attached test case (which passes).

Do you want to describe your situation a bit more?

**Comment by jon-bell** [comment]
@qorost Does this address your problem?

**Comment by qorost** [comment]
@jon-bell Thanks for the quick reply. I am wondering how to turn on the implicit mode, by setting the `Configuration.IMPLICIT_LIGHT_TRACKING` to `true`?

**Comment by jon-bell** [comment]
You should use the `-controlTrack` flag when instrumenting the JRE.

**Comment by qorost** [comment]
@jon-bell Thanks jon. It works now. By the way, would you give some more explanation on how to test the code with `maven verify`, like how to test the file you added for my issue. Thanks again.

**Comment by jon-bell** [comment]
`mvn verify` will run all of the tests. Add `-DskipInTagTests -DskipObjTagTests` and or `-DskipImplicitTests` to skip one of the test configurations. You can add new JUnit tests, as long as they follow this naming scheme (XXXXObjTagITCase etc).

**Comment by qorost** [comment]
thanks for the information.
