### ISSUE TITLE
"Method code too large" when using controlTrack option to instrument JDK/DaCapo

### ISSUE THREAD

**Issue by Waldo1637** [gmu-swe/phosphor#62]
Running Ubuntu 18.04 with OpenJDK 8 installed via apt (Runtime Environment: 1.8.0_181-8u181-b13-0Ubuntu0.18.04.1-b13).
Phosphor built via `mvn package` from commit 8d396effcf461d40b83e614c77d1461173caf945 (i.e. master branch of Programming-Systems-Lab/phosphor).
I believe the only change from that commit was modifying the taint-sources and taint-sinks files to use the lines which are currently commented (i.e. the sources and sinks in the standard java library) and updating the `instrumentJRE.sh` script to use the aforementioned files.
Running the instrumentJRE.sh script results in the "Method code too large" exception while generating `target\jre-inst-implicit` and processing class `sun.security.tools.keytool.Main`.
I understand what the exception means and why it's happening but do you have any solution for it? Perhaps some way of automatically splitting up methods that are too large after instrumentation?
This same issue is even more prevalent when continuing on to instrument the DaCapo benchmarks.
Is there any way to successfully instrumented the DaCapo benchmarks with the `controlTrack` flag?

**Comment by jon-bell** [comment]
This is unfortunately current known limitation. There may be some way to split up the methods, but I haven't had any time to get into it, and it hasn't been a blocker for any of my personal projects yet. I would welcome any attempts to do so.

**Comment by jon-bell** [comment]
Another option is that it might be possible to optimize the code generated in these cases in order to reduce the size of what's generated

**Comment by jon-bell** [comment]
Another thing that comes to mind is bulk pop'ing of taint tags when exiting control of branches.

Is this something that you are interested in trying to put some time into resolving, or hoping someone else will fix? It is not very likely that I will personally have time to get to this in the foreseeable future, but I am happy to help direct you or someone else.

**Comment by Waldo1637** [comment]
Likewise, I do not have time to delve further into this in the foreseeable future. I do appreciate your quick feedback though to let me know this was a known issue and not simply due to a mistake in the setup on my part.

**Comment by jon-bell** [comment]
OK - I've updated the documentation to make this clearer as a fix, and will close this off for now then.

**Comment by jon-bell** [comment]
FYI - as of 0d4bec67bd48dcdd3b14a64e09de5fbd8e846228 this is now fixed, and DaCapo can be instrumented and executed with control track enabled.
