### ISSUE TITLE
No taint is returned when calling equals on tainted string

### ISSUE THREAD

**Issue by miguelvelezmj25** [gmu-swe/phosphor#70]
Hello Professor,

I am not getting a taint in the following scenario:

```
String name = "Miguel"

if(TAINT) {
    name = "Velez";
}

sink(name.equals("Miguel"));  // Should return taint
```

Do you know why I am getting no taint at the sink?

Thanks.

**Comment by miguelvelezmj25** [comment]
I do not think that changing what happens in IF_ACMPEQ will work. When we do something like s.equals(s1), it returns a boolean (i.e., 0 or 1) and the result is then used in an IF<cond> instruction (e.g., IFEQ). 

If you do something like s == s1, then yes, we can check the taints of the objects in IF_ACMP<cond>.

I think that in order for the taint to be caught, we need to:
1. Identify that the result of .equals was used in a sink
2. Identify what objects were used in .equals
3. Pass those objects to the sink

**Comment by jon-bell** [comment]
My point is that s.equals(s1) is failing to return a taint because it's getting lost in the IF_ACMPEQ in the implementation of equals

**Comment by miguelvelezmj25** [comment]
I see what you are saying. Let me look at that.

**Comment by miguelvelezmj25** [comment]
Yes, I had a question about this. In DataAndControlFlowTagFactory.jumpOP is where control flow decisions are handled when doing control tracking. I understand the logic in this class, if there is a control flow decision that depends on a taint, push the taint to the controltainttagstack. However, I do not understand why you removed the pushing logic for the IFNULL and IFNONNULL instructions? And, why there is no pushing logic in the IF_ACMP<cond> instructions?

**Comment by miguelvelezmj25** [comment]
But couldn't the reference be tainted?

```
Car c = new Car();
c.setBrand(source());
```

The value of c.brand is tainted, but you could also say that c, the object, is tainted as well.

**Comment by jon-bell** [comment]
The Car object that c points to is tainted, but the reference `c` is not.

`Car c = new Car();
Car d = c;
c.setBrand(source()); //Both `c` and `d` are tainted here
if(source())
   d = null; //If this runs, we won't be able to taint d
`

**Comment by miguelvelezmj25** [comment]
So ```d``` is not tainted if the then branch is executed?

**Comment by jon-bell** [comment]
Hmm... if it's not taken, then yes I think it should be getting tainted under our semantics.

**Comment by miguelvelezmj25** [comment]
Going back to the IF_ACMPEQ in String.equals, I am struggling to make the changes in DataAndControlFlowTagFactory.jumpOp to not lose the taint information. I thought about pushing the taints of ```this``` and ```object``` on the control stack, but I am not sure how to pop them before the method returns. I also thought about combining the tags of ```this``` and ```object```,  storing the taint in a local variable and assigning that variable to the taint field of the object that is return. However, It seems that I would need to do some tracking outside the jumpOp method.

Am I on the right track?

**Comment by jon-bell** [comment]
You're on the right track. You should let Phosphor handle the pop'ing - it already has all of the code for doing the post dominator analysis etc. If you do to the push'ing, does it generate code to do the pop'ing?

**Comment by miguelvelezmj25** [comment]
I made the changes to ControlTaintTagStack.

However, I am getting an error with the bootclasspath

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000000000000, pid=14934, tid=0x0000000000001703
#
# JRE version:  (8.0_162-b12) (build )
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.162-b12 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  0x0000000000000000
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/mvelezce/Documents/Programming/Java/Projects/phosphor/Phosphor/scripts/run-instrumented/implicit-optimized/hs_err_pid14934.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
```

I copied and paste the java.lang.String source file in another project and generated the .class file. I then added the .class file to Phosphor/override/java/lang (i.e., at the same level of src/, target/, etc). I then did ```./target/jre-inst-implicit/bin/java -Xbootclasspath/p:./override:./target/Phosphor-0.0.4-SNAPSHOT.jar -javaagent:./target/Phosphor-0.0.4-SNAPSHOT.jar -cp PATH_TO_APP_JAR MAIN_CLASS```.

Is there something that I am not typing correctly?

**Comment by jon-bell** [comment]
You should instrument the exact same String.class file that is in your JRE that you are running. You can unzip the rt.jar file to isolate it

**Comment by miguelvelezmj25** [comment]
Thank you. That worked. I had to also instrument String$1.class and String$CaseInsensitiveComparator.class, but it worked. And now I am getting what I expected.

I have a question about my instrumentation. Here is what the top of the decompile String.equals method looks like: 
```
  public TaintedBooleanWithObjTag equals$$PHOSPHORTAGGED(Object var1, ControlTaintTagStack var2, TaintedBooleanWithObjTag var3) {
    EnqueuedTaint var4 = null;
    Object var5 = null;
    EnqueuedTaint var6 = null;
    EnqueuedTaint var7 = null;
    EnqueuedTaint var8 = null;
    EnqueuedTaint var9 = null;
    EnqueuedTaint var10 = null;
    EnqueuedTaint var11 = null;

    try {
      TaintedCharWithObjTag var10000 = new TaintedCharWithObjTag();
      Taint.combineTagsOnObject(var10000, var2);
      TaintedCharWithObjTag var12 = var10000;
      var4 = var2.push(var1, var4); // ----> pushing var4
      var4 = var2.push(this, var4); // ----> pushing var4
      Taint var25;
      if (TaintUtils.ensureUnboxed(this) == TaintUtils.ensureUnboxed(var1)) {
        var25 = var2.copyTag();
        var2.pop(var4); // ----> popping var4 only once
        var2.pop((EnqueuedTaint)var5);
        var2.pop(var7);
        var2.pop(var8);
        var2.pop(var10);
        var2.pop(var11);
        var2.pop(var6);
        var2.pop(var9);
        var3.val = true;
        var3.taint = var25;
        return var3;
      } 
```

Does it matter that I am pushing twice the same EnqueuedTaint, but only popping it once? I see that in IF_ICMP, where two taints are pushed, two different EnqueuedTaint are used.

**Comment by jon-bell** [comment]
Yes - it does matter. You should push the second one to `ta.taintTagsLoggedAtJumps[branchStarting+1]` (like for `IF_ICMPEQ`)

**Comment by miguelvelezmj25** [comment]
Thank you!
